---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-pug-templates/app:0.1.2-alpine
    volumes:
      - ./includes:/usr/src/app/includes
      - ./layouts:/usr/src/app/layouts
      - ./mixins:/usr/src/app/mixins
      - ./tests:/usr/src/app/tests
      - ./.npmignore:/usr/src/app/.npmignore
      - ./CHANGELOG.md:/usr/src/app/CHANGELOG.md
      - ./CONTRIBUTING.md:/usr/src/app/CONTRIBUTING.md
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./LICENSE.md:/usr/src/app/LICENSE.md
      - ./package.json:/usr/src/app/package.json
      - ./README:/usr/src/app/README

  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/public/index.html
      - ./tests/public:/usr/share/nginx/html/public/develop
    ports:
      - "9000:9000"
